name: Hello World Action

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows you to manually trigger the action

jobs:
  hello_world_job:
    runs-on: ubuntu-latest  # You can use other runners like windows-latest or macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository's code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install any required dependencies

      - name: Run Hello World script
        run: |
          python hello-world.py  # Run the Python script
