name: Generate and Zip Content

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Manually trigger from GitHub Actions UI

jobs:
  generate_content_job:
    runs-on: ubuntu-latest  # You can change to macos-latest or windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out your code repository

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Set the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyzipper  # Install the required libraries
          # Optional: If google-genai is not available, you could add a mock or alternative
          # pip install some-mock-library

      - name: Run the Python script
        run: |
          python hello-world.py  # Run the Python script to generate content and create a zip file

      - name: Upload ZIP file as an artifact
        uses: actions/upload-artifact@v4  # Upload the generated zip file
        with:
          name: api-response-zip
          path: api_response.zip  # The zip file created in the script
