name: Hello World Action

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions UI

jobs:
  hello_world_job:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu machine
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your repository's code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyzipper  # Install the required dependencies

      - name: Run Hello World script
        run: |
          python hello-world.py  # Run the Python script to send API request, zip the file, and protect it

      - name: Upload zip file to GitHub
        uses: actions/upload-artifact@v2  # Use v2 instead of v3
        with:
          name: api-response
          path: api_response.zip  # Upload the zip file created by the script
