name: Hello World Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest  # Runs the job on Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your repository's code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-genai requests pyzipper  # Install the required dependencies

      - name: Run Python script
        run: |
          python hello-world.py  # Run the Python script

      - name: Upload ZIP file to GitHub
        uses: actions/upload-artifact@v4  # Upload the generated ZIP file as an artifact
        with:
          name: api-response
          path: api_response.zip  # Path to the zip file to be uploaded
